all:
	(cd AR;                make -f Makefile)
	(cd AR2;               make -f Makefile)
	(cd KPM;               make -f Makefile)

clean:
	(cd AR;                make -f Makefile clean)
	(cd AR2;               make -f Makefile clean)
	(cd KPM;               make -f Makefile clean)
